### ISSUE TITLE
polar_plot does not respect order of factor levels in facet

### ISSUE THREAD

**Issue by mooibroekd** [jack-davison/ggopenair#1]
I have just noticed that the `ggopenair::polar_plot` does not respect the order of factor levels in the column that is provided to the facet parameter (if this is indeed a factor).

The function plots the output with the values in the column used to display facets sorted alphabetically. 

Workaround:
```
p +
  facet_wrap(~ facet_col)
```

**Comment by jack-davison** [comment]
Hi Dennis,

This should be fixed now:

```r
dat <- openair::importAURN("my1", 2020)

polar_plot(dat, "o3", facet = "month") +
  scale_opencolours_c() +
  theme_polar() +
  ggplot2::scale_y_continuous(breaks = seq(0, 15, 5)) +
  annotate_polar_axis(breaks = c(5, 10, 15))
```

![image](https://user-images.githubusercontent.com/45171616/229344965-90dca1cb-ebed-4029-b4d2-eef007240ce1.png)
