### ISSUE TITLE
allow labels in annotate_polar_axis

### ISSUE THREAD

**Issue by schonhose** [jack-davison/ggopenair#2]
Currently the function `ggopenair::annotate_polar_axis` uses the provided breaks as characters to plot. However, it is currently not possible to plot predefined text labels.

For example, if I want to emulate the `openair` labels, I want to add "ws" to the third element of the breaks.

**Comment by jack-davison** [comment]
This should now be fixed:

```r
axis <- labs <- seq(2.5, 12.5, 2.5)
labs[2] <- paste(labs[2], "ws")

polar_plot(marylebone, "o3") +
  theme_polar() +
  scale_opencolours_c("viridis") +
  annotate_polar_axis(breaks = axis,
                      labels = labs,
                      color = "grey80")
```

![image](https://user-images.githubusercontent.com/45171616/229343620-0cd946d4-d6b4-4bee-b69c-783adc3cf03c.png)

**Comment by schonhose** [comment]
Thanks! Has this also been applied to `openairmaps` for consistency?

**Comment by jack-davison** [comment]
`openairmaps` uses the original `openair` to create its polar markers.

`ggopenair` is still too early in development to be implemented into `openairmaps`, really.
